HTML Email template for Totango and beyond!
cloudbees/design-playground pull request #3
Opened 2019-06-26 18:25 UTC by chadbercea

This commit covers the base starting point for html email tempaltes. This is ready to work wtih Totango.

2019-06-26 18:47 UTC, chadbercea commented
@tfoxnc this bad boy is ready for you to review!

2019-08-09 16:50 UTC, tfoxnc requested changes

2019-08-09 16:50 UTC, tfoxnc commented on Product Customer Newsletter Email Template/email-basic-template.html
> +                                                    <p>With that said, would you like to keep this tempalte in Github, or would you like the code pasted in a Confluence page ready to copy and paste?<
```suggestion
                                                    <p>With that said, would you like to keep this template in Github, or would you like the code pasted in a Confluence page ready to copy and paste?</p>
```

2019-08-09 16:50 UTC, tfoxnc commented on Product Customer Newsletter Email Template/email-basic-template.html
> +        <title>Email Title</title>
```suggestion
        <title>Email title</title>
```

2019-08-09 16:50 UTC, tfoxnc commented on Product Customer Newsletter Email Template/email-basic-template.html
> +        <title>Email Title</title>
Our style guide says to use sentence capitalization for titles.

2019-08-09 16:51 UTC, tfoxnc commented
I would rather keep it in GitHub since it is code and easier to suggest code changes in GitHub.

2024-01-02 19:41 UTC, closed without merging